---
version: 2.0.0-rc.5
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing. Change the default admin password before first start.
url: https://github.com/noudAndi/cups-addon
arch:
  - aarch64
  - amd64
hassio_api: true
host_network: true
map:
  - data:rw
  - share:rw
init: false
webui: http://[HOST]:[PORT:631]
options:
  admin_username: "printadmin"
  admin_password: "change_me_now"
  force_regenerate_config: false
  enable_avahi: true
schema:
  admin_username: str
  admin_password: password
  force_regenerate_config: bool
  enable_avahi: bool
startup: services
