---
version: 1.0.0
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/arest/cups-addon
codenotary: andrea_restello@yahoo.it
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
map:
  - data:rw
  - share:rw
init: false
webui: http://[HOST]:631
options:
  admin_username: "printadmin"
  admin_password: "change_me_now"
  force_regenerate_config: false
  enable_avahi: true
schema:
  admin_username: str
  admin_password: password
  force_regenerate_config: bool
  enable_avahi: bool
startup: services
