---
ENABLE_LINTERS:
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GITLEAKS
  - YAML_YAMLLINT

VALIDATE_ALL_CODEBASE: true

FILTER_REGEX_EXCLUDE: |
  (\.git/|\.vscode/)
